export const CHANGE_INPUT = "CHANGE_INPUT"
export const IS_ADMIN = "IS_ADMIN"
export const ADD_TODO = "ADD_TODO"
export const REMOVE_TODO = "REMOVE_TODO"
export const CHECK_TODO = "CHECK_TODO"
export const ADD_ROME = "ADD_ROME"